// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Cuid = require("cuid");

function get(prim) {
  return Cuid();
}

exports.get = get;
/* cuid Not a pure module */
