// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Deepmerge = require("deepmerge");

function merge(prim, prim$1) {
  return Deepmerge(prim, prim$1);
}

exports.merge = merge;
/* deepmerge Not a pure module */
