// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Dotenv = require("dotenv");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function config(path, encoding, param) {
  var tmp = { };
  if (path !== undefined) {
    tmp.path = Caml_option.valFromOption(path);
  }
  if (encoding !== undefined) {
    tmp.encoding = Caml_option.valFromOption(encoding);
  }
  var options = tmp;
  Dotenv.config(options);
  return /* () */0;
}

exports.config = config;
/* dotenv Not a pure module */
