// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var RequireAll = require("require-all");

function exec(prim) {
  RequireAll(prim);
  return /* () */0;
}

exports.exec = exec;
/* require-all Not a pure module */
