// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Shelljs = require("shelljs");

function cp(options, src, dst) {
  if (options !== undefined) {
    Shelljs.cp(options, src, dst);
    return /* () */0;
  } else {
    Shelljs.cp(src, dst);
    return /* () */0;
  }
}

function ln(options, src, dst) {
  if (options !== undefined) {
    Shelljs.ln(options, src, dst);
    return /* () */0;
  } else {
    Shelljs.ln(src, dst);
    return /* () */0;
  }
}

function ls(options, dir) {
  if (options !== undefined) {
    return Shelljs.ls(options, dir);
  } else {
    return Shelljs.ls(dir);
  }
}

function mkdir(options, dir) {
  if (options !== undefined) {
    Shelljs.mkdir(options, dir);
    return /* () */0;
  } else {
    Shelljs.mkdir(dir);
    return /* () */0;
  }
}

function echo(prim) {
  Shelljs.echo(prim);
  return /* () */0;
}

function exec(prim) {
  Shelljs.exec(prim);
  return /* () */0;
}

exports.cp = cp;
exports.echo = echo;
exports.exec = exec;
exports.ln = ln;
exports.ls = ls;
exports.mkdir = mkdir;
/* shelljs Not a pure module */
