// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var NodeYaml = require("node-yaml");

function parse(prim) {
  return NodeYaml.parse(prim);
}

exports.parse = parse;
/* node-yaml Not a pure module */
