// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Fs$LidcoreBsNode = require("@lidcore/bs-node/src/fs.js");
var Instances$LidcoreDraco = require("./lib/instances.js");
var RequireAll$LidcoreDraco = require("./bindings/requireAll.js");

var instancesDir = "" + (String(__dirname) + "/../../../../src/instances");

if (Fs$LidcoreBsNode.existsSync(instancesDir)) {
  RequireAll$LidcoreDraco.exec(instancesDir);
}

Instances$LidcoreDraco.Runtime[/* run */2](/* () */0);

/* instancesDir Not a pure module */
