// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Fs$LidcoreBsNode = require("@lidcore/bs-node/src/fs.js");
var Shell$LidcoreDraco = require("./bindings/shell.js");
var DracoCommon$LidcoreDraco = require("./bin/dracoCommon.js");

var functionsDir = "" + (String(__dirname) + "/../../../../src/functions");

var group = { };

var config = DracoCommon$LidcoreDraco.config(/* () */0);

if (Fs$LidcoreBsNode.existsSync(functionsDir)) {
  $$Array.iter((function (file) {
          return $$Array.iter((function (param) {
                        group[param[0]] = param[1];
                        return /* () */0;
                      }), Js_dict.entries(require(file)));
        }), Shell$LidcoreDraco.ls(undefined, "" + (String(functionsDir) + "/*.js")));
}

module.exports[config.functions.group] = group;

/* functionsDir Not a pure module */
